[package]
name = "stracture-sample"
version = "0.1.0"
authors = ["ali izadi <a.izadi@mail.tourismit.ir>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
